In [1]:
import torch

In [3]:
torch.tensor(9)

tensor(9)

In [4]:
revenue = torch.tensor([100,120,90,75])
revenue

tensor([100, 120,  90,  75])

In [6]:
revenue[0]

tensor(100)

In [7]:
revenue[:3]

tensor([100, 120,  90])

In [9]:
# Sales data for Quater 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = torch.tensor([
    [200,220,250], # Product A (iPhone)
    [150, 180,210], # Product B (iPod)
    [300, 330, 360] #Product C (MacBook)
])

q2 = torch.tensor([
    [209, 231, 259], # Product A(iPhone)
    [155, 192, 222], # Product B (iPad)
    [310, 340, 375] # Product C (MacBook)
])




In [10]:
q1 + q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [11]:
q2 -q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [12]:
units = torch.tensor([
    [200,220], # Product A (iPhone)
    [150,180], # Product B (iPad)
    [300,330] # Product C (MacBook)
],dtype=float)

In [13]:
units.shape

torch.Size([3, 2])

In [14]:
units.dtype

torch.float64

In [15]:
units.view(6)

tensor([200., 220., 150., 180., 300., 330.], dtype=torch.float64)

In [17]:
units.view(1,6)

tensor([[200., 220., 150., 180., 300., 330.]], dtype=torch.float64)

In [18]:
units

tensor([[200., 220.],
        [150., 180.],
        [300., 330.]], dtype=torch.float64)

In [20]:
units[2,1]

tensor(330., dtype=torch.float64)

In [21]:
units[2,1] = 389

In [22]:
units

tensor([[200., 220.],
        [150., 180.],
        [300., 389.]], dtype=torch.float64)

In [23]:
material_cost = torch.tensor(10,requires_grad=True,dtype=torch.float16)
labor_cost = torch.tensor(5, requires_grad=True,dtype=torch.float16)
total_cost = 3 * material_cost**2 + 5 * labor_cost + 100
total_cost

tensor(425., dtype=torch.float16, grad_fn=<AddBackward0>)

In [24]:
total_cost.backward()
material_cost.grad, labor_cost.grad

(tensor(60., dtype=torch.float16), tensor(5., dtype=torch.float16))

In [25]:
x = torch.tensor(4, requires_grad=True,dtype=torch.float16)
y = x**2 +5

y.backward()
x.grad

tensor(8., dtype=torch.float16)

In [30]:
a = torch.tensor([1,2,3],requires_grad=True,dtype=torch.float16)
b = 2 ** a ** 3 + 7
b

tensor([  9., 263.,  inf], dtype=torch.float16, grad_fn=<AddBackward0>)

In [32]:
result = b.sum()
result.backward()
a.grad

tensor([   4.1602, 2130.0000,       inf], dtype=torch.float16)