In [14]:
import torch
import torch.nn as nn 
import torch.optim as optim
import pandas as pd

In [15]:
df = pd.read_csv("bonus.csv")
df.head()

employee_id  performance  years_of_experience  projects_completed  bonus
0     EMP_001            7                    1                   3    116
1     EMP_002            4                    8                  10    136
2     EMP_003            8                    4                   5    150
3     EMP_004            5                    4                   7    118
4     EMP_005            7                    5                   6    146

In [16]:
df.shape

(1000, 5)

In [17]:
from sklearn.model_selection import train_test_split

X = df[['performance','years_of_experience','projects_completed']].values
y = df[['bonus']].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=40)

In [18]:
X_train.shape

(800, 3)

In [19]:
X_test.shape

(200, 3)

In [20]:
X_train_tensor = torch.tensor(X_train,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test,dtype=torch.float32)

In [21]:
class BonusPredictor(nn.Module):
    def __init__(self):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(3,1) # 3 input features, 1 output neuron
        )
    
    def forward(self, x):
        return self.network(x)




In [26]:
model = BonusPredictor()
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr = 0.005)

In [27]:
epochs = 5000

for epoch in range(epochs) :
    # 1. Forward pass
    predictions = model(X_train_tensor)
    loss = criterion(predictions,y_train_tensor)
    # 2. Backward pass
    optimizer.zero_grad()
    loss.backward()
    # Update Weights
    optimizer.step()

    #Print Loss every 100 epochs

    if(epoch+1) % 100 == 0:
        print(f"Epoch [{epoch +1}/{epoch}], loss: {loss.item():2f}")


Epoch [100/99], loss: 20.962872
Epoch [200/199], loss: 18.330046
Epoch [300/299], loss: 16.111219
Epoch [400/399], loss: 14.189722
Epoch [500/499], loss: 12.507271
Epoch [600/599], loss: 11.027678
Epoch [700/699], loss: 9.724285
Epoch [800/799], loss: 8.575357
Epoch [900/899], loss: 7.562288
Epoch [1000/999], loss: 6.668959
Epoch [1100/1099], loss: 5.881165
Epoch [1200/1199], loss: 5.186441
Epoch [1300/1299], loss: 4.573772
Epoch [1400/1399], loss: 4.033497
Epoch [1500/1499], loss: 3.557019
Epoch [1600/1599], loss: 3.136844
Epoch [1700/1699], loss: 2.766297
Epoch [1800/1799], loss: 2.439522
Epoch [1900/1899], loss: 2.151348
Epoch [2000/1999], loss: 1.897214
Epoch [2100/2099], loss: 1.673104
Epoch [2200/2199], loss: 1.475466
Epoch [2300/2299], loss: 1.301181
Epoch [2400/2399], loss: 1.147474
Epoch [2500/2499], loss: 1.011926
Epoch [2600/2599], loss: 0.892391
Epoch [2700/2699], loss: 0.786974
Epoch [2800/2799], loss: 0.694012
Epoch [2900/2899], loss: 0.612030
Epoch [3000/2999], loss: 0.5

In [29]:
model.eval()

with torch.no_grad():
    test_predictions = model(X_test_tensor)
    test_loss = criterion(test_predictions,y_test_tensor)

print(f"Test Loss: {test_loss.item():0.02f}")

Test Loss: 0.05


In [30]:
X_test_tensor[:3]

tensor([[ 3.,  5.,  8.],
        [ 5.,  1.,  2.],
        [ 4.,  9., 10.]])

In [31]:
test_predictions[:3]

tensor([[102.0458],
        [ 89.5998],
        [141.8253]])

In [32]:
y_test_tensor[:3]

tensor([[102.],
        [ 90.],
        [142.]])

In [34]:
#w1, w2, w3, b
for name, value in model.named_parameters():
    print(f"Name: {name}, Value: {value}")

Name: network.0.weight, Value: Parameter containing:
tensor([[12.0339,  5.8404,  2.1921]], requires_grad=True)
Name: network.0.bias, Value: Parameter containing:
tensor([19.2058], requires_grad=True)
